version: "3"
services:
  node:
    image: service-app:app
    build: .
    ports:
     - ${PORT}:${PORT}
    depends_on:
     - postgres
    environment:
     - PORT=${PORT}
    restart: always
  postgres: 
    image: service-db:db
    build: ./database/
    ports: 
     - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
     POSTGRES_USER: ${POSTGRES_USER}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
     POSTGRES_DB: ${POSTGRES_DB}
    restart: always
networks:
  default:
    name: lib-net
    external: true
  
