version: "3"
services:
  node:
    container_name: server
    build: .
    ports:
     - ${PORT}:${PORT}
    depends_on:
     - postgres
    environment:
     - PORT=${PORT}
    restart: always
    networks: 
      - postgres
  postgres: 
    build: ./database/
    ports: 
     - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
     POSTGRES_USER: ${POSTGRES_USER}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
     POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    restart: always
    networks: 
      - postgres
networks:
  postgres:
    driver: bridge
