version: "3"
services:
  node:
    build: .
    ports:
     - ${PORT}:${PORT}
    depends_on:
     - postgres
    environment:
     - PORT=${PORT}
    restart: always
  postgres: 
    build: ./database/
    ports: 
     - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
     POSTGRES_USER: ${POSTGRES_USER}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
     POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    restart: always
networks:
  default:
    name: lib-net
    external: true
  
